---
openapi: 3.0.1
info:
  title: API V1
  version: v1
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: bearerAuth
    in: header
paths:
  "/schools/{school_id}/classes/{klass_id}/students":
    get:
      summary: Вывести список студентов класса
      tags:
      - students
      - classes
      parameters:
      - name: school_id
        in: path
        required: true
        schema:
          type: string
      - name: klass_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Список студентов
  "/schools/{school_id}/classes":
    get:
      summary: Вывести список классов школы
      tags:
      - classes
      parameters:
      - name: school_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Список классов
  "/students":
    post:
      summary: Регистрация нового студента
      tags:
      - students
      parameters: []
      responses:
        '201':
          description: Successful operation
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - first_name
              - last_name
              - surname
              - klass_id
              - school_id
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                surname:
                  type: string
                klass_id:
                  type: integer
                school_id:
                  type: integer
  "/students/{user_id}":
    delete:
      summary: Удалить студента
      tags:
      - students
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      security:
      - bearerAuth: []
      responses:
        '204':
          description: Successful operation
        '400':
          description: Некорректный id студента
        '401':
          description: Некорректная авторизация
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
